# fly.toml app configuration file generated for server-crimson-sea-5318 on 2024-07-07T23:36:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-crimson-sea-5318'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
